### ISSUE TITLE
!uwu command not working with a certain string

### ISSUE THREAD

**Issue by b-coimbra** [Demonstrandum/Simp-O-Matic#30]
`!uwu test` does not return anything :shrug:

**Comment by Demonstrandum** [comment]
úr fault

**Comment by Demonstrandum** [comment]
`TypeError: undefined is not a function.`

Traceback:
https://github.com/OMatics/Simp-O-Matic/blob/a872275cd374b4cade1f4d8ef4bc88d2c3cff557/lib/commands/uwu.ts#L92
https://github.com/OMatics/Simp-O-Matic/blob/a872275cd374b4cade1f4d8ef4bc88d2c3cff557/lib/commands/uwu.ts#L127
```
<anonymous>
```
https://github.com/OMatics/Simp-O-Matic/blob/a872275cd374b4cade1f4d8ef4bc88d2c3cff557/lib/commands/uwu.ts#L142
```
main.js:__:__
```
etc.

**Comment by Demonstrandum** [comment]
Relevant:
https://github.com/nodejs/node/issues/15645

**Comment by b-coimbra** [comment]
Fix [#96c771](https://github.com/OMatics/Simp-O-Matic/commit/96c771b9aa82ac385d58c65068baf5a1169478a8)
